### ISSUE TITLE
change luxor api key implementation

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [PlebeiusGaragicus/bitcoin-mining-calculator#22]
Instead of putting the Luxor API key in apikey.py we should put it in a file called apikey and have run_calculator.py search for this file, and if found, include it as a command-line argument to main.py  The file apikey's contents can just be the bare API key with no metadata

Please reference this issue in the Pull Request that resolves it.

**Comment by suchdatums** [comment]
resolved is latest PR

**Comment by PlebeiusGaragicus** [comment]
indubitably
